Repository dandi/dandi-archive, pull requests merged in 2022-12, with the labels that each got.

#1386 dandi-archive web app readme edit
  web/README.md
Labels: documentation

#1390 Always clear checksum files during zarr ingestion
  dandiapi/zarr/tasks/__init__.py
  dandiapi/zarr/tests/test_zarr_checksums.py
Labels: patch, release

#1393 Refresh asset object before validating it after creation
  dandiapi/api/services/asset/__init__.py
Labels: patch, release

#1379 Move metadata validation tasks into the service layer
  dandiapi/api/management/commands/create_dev_dandiset.py
  dandiapi/api/management/commands/revalidate.py
  dandiapi/api/services/asset/metadata.py
  dandiapi/api/services/metadata/__init__.py
  dandiapi/api/services/metadata/exceptions.py
  dandiapi/api/tasks/__init__.py
  dandiapi/api/tasks/scheduled.py
  dandiapi/api/tests/factories.py
  dandiapi/api/tests/test_tasks.py
  dandiapi/api/tests/test_unembargo.py
  dandiapi/api/tests/test_version.py
Labels: internal

#1376 Optimize memory use in publish service
  dandiapi/api/services/publish/__init__.py
Labels: internal

#1399 Move asset publishing to publish service
  dandiapi/api/models/asset.py
  dandiapi/api/services/publish/__init__.py
  dandiapi/api/tests/factories.py
  dandiapi/api/tests/test_asset.py
  dandiapi/api/tests/test_asset_paths.py
  dandiapi/api/tests/test_tasks.py
  dandiapi/api/tests/test_version.py
Labels: internal

#1402 Manage CI dependencies with dependabot
  .github/dependabot.yml
  setup.py
  tox.ini
Labels: internal

#1394 Use flat file listing in zarr file browser
  dandiapi/api/tests/test_asset.py
  dandiapi/api/views/asset.py
  dandiapi/urls.py
  dandiapi/zarr/tests/test_zarr.py
  dandiapi/zarr/views/__init__.py
Labels: patch, release
