Repository dandi/dandi-archive, pull requests merged in 2022-05, with the labels that each got.

#1084 Extend docs with information about devel env
  DEVELOPMENT.md
  web/README.md
Labels: documentation

#1087 BF DOC(incomplete): /zarr/.../ingest has 204 not 200 response
  dandiapi/api/views/zarr.py
Labels: documentation

#1088 Fix opening Meditor when clicking on "Fix Issues" in the list of dandiset metadata issues
  web/src/views/DandisetLandingView/DandisetPublish.vue
Labels: UX, patch

#1101 BF: provide custom commit message without token to skip the beat
  .github/workflows/release.yml
Labels: release, internal
