Repository dandi/dandi-archive, pull requests merged in 2022-07, with the labels that each got.

#1152 Use `logging.info` for user errors instead of `logging.error`
  dandiapi/api/models/version.py
  dandiapi/api/models/zarr.py
  dandiapi/api/tasks/__init__.py
Labels: patch, release

#1154 Fix missing zarr_id in `cancel_zarr_upload`
  dandiapi/api/tests/test_unembargo.py
  dandiapi/api/tests/test_zarr_upload.py
  dandiapi/api/views/zarr.py
  dandiapi/settings.py
Labels: patch, release

#1159 Fix excessive memory usage in asset summary calculation
  dandiapi/api/models/version.py
Labels: patch, release

#1134 Optimize dandiset list endpoint
  dandiapi/api/tests/test_dandiset.py
  dandiapi/api/views/dandiset.py
  dandiapi/api/views/serializers.py
  dandiapi/settings.py
  web/src/components/DandisetList.vue
  web/src/components/DandisetsPage.vue
Labels: release

#1164 Fix race condition in sha256 calculation
  dandiapi/api/tasks/__init__.py
  dandiapi/api/tests/test_tasks.py
Labels: patch, release

#1169 Improve load times of admin pages
  dandiapi/api/admin.py
  dandiapi/api/dashboard.py
Labels: patch, release

#1185 Fix admin search fields
  dandiapi/api/admin.py
Labels: patch, release

#1187 Add time limits to celery tasks
  dandiapi/api/scheduled_tasks.py
  dandiapi/api/tasks/__init__.py
  dandiapi/api/tasks/zarr.py
Labels: patch

#1184 Improve manifest file writing performance
  Procfile
  dandiapi/api/manifests.py
  dandiapi/api/tasks/__init__.py
Labels: patch, release

#1122 Add publish "checklist"
  web/src/views/DandisetLandingView/DandisetPublish.vue
Labels: patch

#1209 Enable Sentry performance tracking
  dandiapi/api/apps.py
  dandiapi/settings.py
Labels: patch, release

#1114 Properly include "data packages" in project
  setup.py
Labels: internal

#1215 Improve sentry configuration
  dandiapi/api/apps.py
Labels: patch, release

#1175 Update Zarr design doc for changes to checksum format
  doc/design/zarr-support-3.md
Labels: documentation

#1216 Add metadata flag for asset listing
  dandiapi/api/tests/test_asset.py
  dandiapi/api/views/asset.py
  dandiapi/api/views/serializers.py
Labels: patch, release
