Repository dandi/dandi-archive, pull requests merged in 2022-11, with the labels that each got.

#1358 Add tqdm to asset path version ingestion
  dandiapi/api/asset_paths.py
  setup.py
Labels: patch, release

#1359 Pin mypy
  tox.ini
Labels: tests

#1360 Separate backend CI into separate jobs
  .github/workflows/backend-ci.yml
Labels: tests

#1366 Save draft versions during asset metadata validation
  dandiapi/api/tasks/__init__.py
  dandiapi/api/tests/test_tasks.py
Labels: patch, release

#1363 Internal publishing service
  dandiapi/api/services/publish/__init__.py
  dandiapi/api/services/publish/exceptions.py
  dandiapi/api/tasks/__init__.py
  dandiapi/api/tests/test_asset_paths.py
  dandiapi/api/tests/test_tasks.py
  dandiapi/api/tests/test_version.py
  dandiapi/api/views/version.py
Labels: internal

#1316 Convert `DandisetLandingView` to `<script setup>`, use `vue-router` composable
  web/src/views/DandisetLandingView/DandisetLandingView.vue
Labels: internal

#1311 Improved pagination design in file browser
  web/src/components/FileBrowser/FileBrowserPagination.vue
  web/src/views/FileBrowserView/FileBrowser.vue
Labels: enhancement

#1374 Fix file browser bug
  web/src/views/FileBrowserView/FileBrowser.vue
Labels: patch, release

#1380 Temporarily pin flake8
  tox.ini
Labels: maintenance

#1383 Fix publishing being allowed for pending assets
  dandiapi/api/services/publish/__init__.py
Labels: patch, release

#1303 Convert `Meditor.vue` to `<script setup>`
  web/src/components/Meditor/Meditor.vue
Labels: internal

#1340 Convert FileBrowser component to <script setup>
  web/src/views/FileBrowserView/FileBrowser.vue
Labels: internal

#1342 Add file upload instructions to file browser UI
  web/src/components/FileBrowser/FileUploadInstructions.vue
  web/src/views/FileBrowserView/FileBrowser.vue
Labels: enhancement, patch, release

#1385 Prevent locking dandisets during zarr upload
  dandiapi/zarr/views/__init__.py
Labels: patch, release
