Repository dandi/dandi-archive, pull requests merged in 2022-04, with the labels that each got.

#999 Allow github login with GET request
  dandiapi/settings.py
Labels: patch, release

#991 Bump dandischema to 0.6.0
  dandiapi/api/models/zarr.py
  dandiapi/api/tasks/zarr.py
  dandiapi/api/tests/test_ingest_zarr_archive.py
  dandiapi/api/tests/test_zarr.py
  dandiapi/api/tests/test_zarr_checksums.py
  dandiapi/api/views/zarr.py
  dandiapi/api/zarr_checksums.py
  setup.py
Labels: patch, release

#1007 Handle validation errors when fetching zarr checksums
  dandiapi/api/models/zarr.py
  dandiapi/api/tests/test_zarr.py
  dandiapi/api/zarr_checksums.py
Labels: patch, release

#1005 Make checksum_worker responsible for zarr ingest
  Procfile
  dandiapi/api/tasks/zarr.py
  docker-compose.override.yml
Labels: release

#1008 Fix search bar overflowing offscreen
  web/src/components/DandisetSearchField.vue
Labels: patch, release

#1009 Remove `models.PROTECT` from `Asset.previous`
  dandiapi/api/migrations/0028_alter_asset_previous.py
  dandiapi/api/models/asset.py
Labels: patch, release

#1014 Fix responsiveness of v-app-bar
  web/src/components/AppBar/AppBar.vue
Labels: patch, release

#1033 Release branch CI
  .github/workflows/backend-production-deploy.yml
  .github/workflows/backend-staging-deploy.yml
  .github/workflows/frontend-production-deploy.yml
  .github/workflows/update-release-branch.yml
  web/netlify.toml
Labels: DX, maintenance, patch, release

#1036 Fix disabled Heroku Github integration for staging and production deployment
  .github/workflows/backend-production-deploy.yml
  .github/workflows/backend-staging-deploy.yml
Labels: patch, release

#1038 Push to heroku directly in update-release-branch.yml
  .github/workflows/backend-production-deploy.yml
  .github/workflows/update-release-branch.yml
Labels: patch, release

#1046 Fix incorrect fields in info endpoint
  dandiapi/api/tests/test_info.py
  dandiapi/api/views/info.py
  dev/.env.docker-compose
  dev/.env.docker-compose-native
Labels: patch, release

#1049 Include `api/` suffix in info endpoint api url
  dandiapi/api/tests/test_info.py
  dandiapi/api/views/info.py
Labels: patch, release

#1053 Change `UserMetadata.user` on_delete to `CASCADE`
  dandiapi/api/migrations/0029_alter_usermetadata_user.py
  dandiapi/api/models/user.py
Labels: patch, release

#1056 Remove trailing slash in info api url
  dandiapi/api/tests/test_info.py
  dandiapi/api/views/info.py
Labels: patch, release

#1050 Misc. Django/Python improvements
  dandiapi/api/dashboard.py
  dandiapi/api/mail.py
  dandiapi/api/management/commands/migrate_published_version_metadata.py
  dandiapi/api/models/dandiset.py
  dandiapi/api/models/version.py
  dandiapi/api/models/zarr.py
  dandiapi/api/tasks/zarr.py
  dandiapi/api/views/asset.py
  dandiapi/api/views/dandiset.py
  dandiapi/api/views/version.py
  dandiapi/api/views/zarr.py
  dandiapi/api/zarr_checksums.py
Labels: maintenance

#560 Add garbage collection design doc
  doc/design/garbage-collection-1.md
Labels: design-doc

#1054 Fix version in `/api/info/`
  .gitattributes
  .github/workflows/frontend-ci.yml
  .github/workflows/update-release-branch.yml
  MANIFEST.in
  dandiapi/__init__.py
  dandiapi/_version.py
  dandiapi/api/tests/test_info.py
  dandiapi/api/views/info.py
  dev/django-public.Dockerfile
  dev/django.Dockerfile
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
  versioneer.py
Labels: patch, release
