Repository dandi/dandi-archive, pull requests merged in 2022-10, with the labels that each got.

#1308 Use `django_filters` instead of DRF for Version viewset filtering
  dandiapi/api/views/version.py
Labels: patch, release

#1309 Update frontend to use new query parameter for version listing endpoint
  web/src/rest.ts
Labels: patch, release

#1310 Add additional waits to account E2E test
  web/test/src/tests/account.test.js
Labels: tests

#1006 Prevent double-publishing
  dandiapi/api/migrations/0037_alter_version_status.py
  dandiapi/api/models/version.py
  dandiapi/api/tasks/__init__.py
  dandiapi/api/tests/test_tasks.py
  dandiapi/api/tests/test_version.py
  dandiapi/api/views/version.py
  web/src/views/DandisetLandingView/DandisetPublish.vue
Labels: patch, release

#1321 Fix 401 errors from `/versions/` endpoint being reported to sentry
  web/src/stores/dandiset.ts
Labels: patch, release

#1324 Update GitHub Actions action versions
  .github/dependabot.yml
  .github/workflows/backend-ci.yml
  .github/workflows/cli-integration.yml
Labels: internal

#1333 Fix mypy errors in `api/admin.py`
  dandiapi/api/admin.py
  pyproject.toml
Labels: internal

#1339 Disable pulling of all Docker images from Docker Hub
  .github/workflows/cli-integration.yml
Labels: tests
