Repository dandi/dandi-archive, pull requests merged in 2022-08, with the labels that each got.

#1202 Use an ordered QuerySet in Zarr viewset
  dandiapi/api/views/zarr.py
Labels: release

#1243 Configure mypy
  mypy.ini
  pyproject.toml
  setup.py
  tox.ini
Labels: tests

#1253 Update assets path pagination
  dandiapi/api/views/asset.py
Labels: patch, release

#1256 Create django app for zarr functionality
  dandiapi/api/admin.py
  dandiapi/api/management/commands/import_dandisets.py
  dandiapi/api/migrations/0034_remove_embargoedzarrarchive_dandiset_and_more.py
  dandiapi/api/migrations/0035_alter_asset_zarr_delete_embargoedzarrarchive_and_more.py
  dandiapi/api/models/__init__.py
  dandiapi/api/models/asset.py
  dandiapi/api/tasks/__init__.py
  dandiapi/api/tests/factories.py
  dandiapi/api/tests/test_version.py
  dandiapi/api/views/__init__.py
  dandiapi/api/views/asset.py
  dandiapi/conftest.py
  dandiapi/settings.py
  dandiapi/urls.py
  dandiapi/zarr/__init__.py
  dandiapi/zarr/admin.py
  dandiapi/zarr/apps.py
  dandiapi/zarr/checksums.py
  dandiapi/zarr/management/commands/ingest_dandiset_zarrs.py
  dandiapi/zarr/management/commands/ingest_zarr_archive.py
  dandiapi/zarr/management/commands/migrate_zarr_checksums.py
  dandiapi/zarr/management/commands/rename_ngff.py
  dandiapi/zarr/migrations/0001_initial.py
  dandiapi/zarr/migrations/__init__.py
  dandiapi/zarr/models.py
  dandiapi/zarr/tasks/__init__.py
  dandiapi/zarr/tests/factories.py
  dandiapi/zarr/tests/test_ingest_zarr_archive.py
  dandiapi/zarr/tests/test_migrate_zarr_checksums.py
  dandiapi/zarr/tests/test_zarr.py
  dandiapi/zarr/tests/test_zarr_checksums.py
  dandiapi/zarr/tests/test_zarr_upload.py
  dandiapi/zarr/views/__init__.py
  pyproject.toml
Labels: patch, release
