Repository dandi/dandi-archive, pull requests merged in 2024-07, with the labels that each got.

#1972 Remove File to avoid confusion
  web/src/views/DandisetLandingView/DandisetMain.vue
Labels: UX

#1976 Bump dandischema to 0.10.2 (schema version 0.6.8)
  dandiapi/api/tests/factories.py
  setup.py
  web/src/components/Meditor/types.ts
Labels: patch, release

#1979 Add dashboard link to view to emit user list as Mailchimp-compatible CSV
  dandiapi/api/templates/dashboard/base.html
  dandiapi/api/views/__init__.py
  dandiapi/api/views/dashboard.py
  dandiapi/urls.py
Labels: patch, release

#1965 Automate dandiset unembargo
  dandiapi/api/mail.py
  dandiapi/api/models/dandiset.py
  dandiapi/api/services/dandiset/__init__.py
  dandiapi/api/services/embargo/__init__.py
  dandiapi/api/services/embargo/exceptions.py
  dandiapi/api/tasks/__init__.py
  dandiapi/api/tasks/scheduled.py
  dandiapi/api/templates/api/mail/dandiset_unembargo_failed.html
  dandiapi/api/templates/api/mail/dandisets_to_unembargo.txt
  dandiapi/api/tests/test_asset.py
  dandiapi/api/tests/test_dandiset.py
  dandiapi/api/tests/test_unembargo.py
  dandiapi/api/tests/test_upload.py
  dandiapi/api/tests/test_version.py
  dandiapi/api/views/asset.py
  dandiapi/api/views/dandiset.py
  dandiapi/api/views/upload.py
  dandiapi/api/views/version.py
  web/src/views/DandisetLandingView/DandisetActions.vue
  web/src/views/DandisetLandingView/DandisetUnembargo.vue
  web/src/views/FileBrowserView/FileBrowser.vue
Labels: patch, release, embargo

#1986 Fix N query problem with VersionStatusFilter
  dandiapi/api/admin.py
Labels: patch, release

#1937 Add retries to sha256 checksum calculation task
  dandiapi/api/tasks/__init__.py
Labels: patch, release
