Repository dandi/dandi-archive, pull requests merged in 2024-10, with the labels that each got.

#1938 Add calculate_sha256 management command to trigger (re)computation for a blob
  .codespellrc
  dandiapi/api/management/commands/calculate_sha256.py
Labels: internal

#2043 Do login into docker hub so we could reliably build our docker image
  .github/workflows/cli-integration.yml
Labels: tests

#2044 Auto-allow people with @alleninstitute.org email addresses
  dandiapi/api/views/auth.py
Labels: administration

#2010 Derive asset `access` field from asset blob
  dandiapi/api/migrations/0011_asset_access_metadata.py
  dandiapi/api/models/asset.py
  dandiapi/api/tests/test_asset.py
Labels: patch, release

#2054 Update new user registration questions
  dandiapi/api/templates/api/account/questionnaire_form.html
  dandiapi/api/views/auth.py
Labels: patch, release

#2045 Add pre-commit config and apply it across codebase
  .pre-commit-config.yaml
  dandiapi/api/templates/api/mail/dandiset_unembargo_failed.html
  doc/design/audit-trail-mvp.md
  doc/design/deployment-1.md
  doc/design/embargo-full.md
  doc/design/garbage-collection-1.md
Labels: DX

#2041 Add neurosift external service for dandisets
  web/src/views/DandisetLandingView/DandisetActions.vue
  web/src/views/DandisetLandingView/ExternalDandisetServicesDialog.vue
Labels: patch, release
