Repository dandi/dandi-archive, pull requests merged in 2024-02, with the labels that each got.

#1852 It is time again to get to the new year and update Copyright statement
  web/src/components/DandiFooter.vue
Labels: internal

#1857 Always rebuild and deploy the frontend
  web/netlify.toml
Labels: patch, release

#1856 Fix documentation about release process to Heroku -- done by GitHub CI now not Heroku itself
  doc/design/deployment-1.md
Labels: documentation, design-doc

#1847 Open asset on click
  web/src/views/FileBrowserView/FileBrowser.vue
Labels: patch, release

#1828 DEVELOPMENT.md: set email to the one known to git
  DEVELOPMENT.md
Labels: documentation, DX

#1800 Don't use .save() in validate_version_metadata
  dandiapi/api/services/metadata/__init__.py
  dandiapi/api/tests/test_tasks.py
Labels: patch, release

#1878 Require v0.60.0 of `dandi-cli`
  dandiapi/api/tests/test_info.py
  dandiapi/api/views/info.py
Labels: patch, release
