Repository dandi/dandi-archive, pull requests merged in 2024-09, with the labels that each got.

#2025 Use bulk_update for updating blob download counts
  dandiapi/analytics/tasks/__init__.py
Labels: patch, release

#2015 Disable GUI "Unembargo" button if there are active uploads
  dandiapi/api/models/version.py
  dandiapi/api/tests/test_dandiset.py
  dandiapi/api/tests/test_version.py
  dandiapi/api/views/serializers.py
  web/src/types/index.ts
  web/src/views/DandisetLandingView/DandisetUnembargo.vue
Labels: patch, release, embargo

#2017 admin view: Also show (list) zarr for Assets view
  dandiapi/api/admin.py
Labels: enhancement, patch, release, zarr

#2026 Manually configure celery to retry connections on startup
  dandiapi/settings.py
Labels: patch, release

#2022 Add text from the Handbook to the rejected user email
  dandiapi/api/templates/api/mail/rejected_user_message.txt
Labels: patch, release

#1952 Only include APPROVED users for stats on homepage
  dandiapi/api/tests/test_stats.py
  dandiapi/api/views/stats.py
Labels: patch, release

#2030 add external neurosift service for .nwb.lindi.tar
  web/src/views/FileBrowserView/FileBrowser.vue
Labels: patch, release

#2019 ../assets/{asset_id}/ PUT: clarify that new asset is created
  dandiapi/api/views/asset.py
Labels: documentation, DX, patch, release

#2035 Fix Dandiset emptiness detection logic
  dandiapi/api/tests/test_dandiset.py
  dandiapi/api/views/dandiset.py
Labels: patch, release
