Repository dandi/dandi-archive, pull requests merged in 2024-12, with the labels that each got.

#2082 Add incomplete upload dialog to DLP when unembargo is blocked
  dandiapi/api/tests/test_dandiset.py
  dandiapi/api/views/dandiset.py
  dandiapi/api/views/serializers.py
  web/src/rest.ts
  web/src/types/index.ts
  web/src/views/DandisetLandingView/DandisetUnembargo.vue
Labels: patch, release

#2062 Fix validation error when only Zarr assets are uploaded
  dandiapi/api/services/metadata/__init__.py
  dandiapi/api/tests/test_tasks.py
Labels: patch, release

#2098 Pin `django-allauth` to 0.61.1
  setup.py
Labels: patch, release

#2099 Bump `django-allauth` to latest version
  dandiapi/api/migrations/0013_remove_assetpath_consistent_slash_and_more.py
  setup.py
Labels: patch, release

#2102 DLP: Have "Cite as" only for OPEN (non embargoed) dandisets
  web/src/views/DandisetLandingView/DandisetActions.vue
Labels: UX

#2076 ENH: run pytest against dandi-cli with -v to see which tests ran
  .github/workflows/cli-integration.yml
Labels: DX, tests

#2079 Add some .debug level messages in tasks upon no action to be performed
  dandiapi/api/doi.py
  dandiapi/api/tasks/__init__.py
  dandiapi/api/tasks/scheduled.py
Labels: DX, internal

#2095 Update instructions for serving the web app through a development server
  web/README.md
Labels: DX

#2108 Update shareable link to reflect window.location.origin
  web/src/views/DandisetLandingView/ShareDialog.vue
Labels: patch, release

#2111 Set version status to PENDING in ingest_zarr_archive
  dandiapi/zarr/tasks/__init__.py
  dandiapi/zarr/tests/factories.py
  dandiapi/zarr/tests/test_ingest_zarr_archive.py
Labels: patch, release

#2103 DLP: Add "Protocols" card
  web/src/components/DLP/OverviewTab.vue
Labels: UX

#2124 Enhance OverviewTab.vue to display Resource Type information for DLP items
  web/src/components/DLP/OverviewTab.vue
Labels: patch, release
