Repository dandi/dandi-archive, pull requests merged in 2025-09, with the labels that each got.

#2500 Switch the default storage to always use `S3Storage`
  dandiapi/api/management/commands/rectify_manifest_tags.py
  dandiapi/api/manifests.py
  dandiapi/api/migrations/0001_initial_v2.py
  dandiapi/api/models/asset.py
  dandiapi/api/models/upload.py
  dandiapi/api/multipart.py
  dandiapi/api/services/embargo/__init__.py
  dandiapi/api/services/embargo/utils.py
  dandiapi/api/services/garbage_collection/__init__.py
  dandiapi/api/services/garbage_collection/upload.py
  dandiapi/api/storage.py
  dandiapi/api/tests/factories.py
  dandiapi/api/tests/test_asset.py
  dandiapi/api/tests/test_audit.py
  dandiapi/api/tests/test_checksum.py
  dandiapi/api/tests/test_create_dev_dandiset.py
  dandiapi/api/tests/test_manifests.py
  dandiapi/api/tests/test_tasks.py
  dandiapi/api/tests/test_unembargo.py
  dandiapi/api/tests/test_upload.py
  dandiapi/api/views/asset.py
  dandiapi/api/views/upload.py
  dandiapi/conftest.py
  dandiapi/settings/development.py
  dandiapi/settings/production.py
  dandiapi/settings/testing.py
  dandiapi/storage.py
  dandiapi/zarr/models.py
  dandiapi/zarr/tests/test_zarr.py
  dandiapi/zarr/tests/test_zarr_upload.py
  dandiapi/zarr/tests/utils.py
  dandiapi/zarr/views/__init__.py
  doc/design/garbage-collection-1.md
  pyproject.toml
  uv.lock
Labels: internal

#2419 Update to Django 5
  dandiapi/api/migrations/0001_initial_v2.py
  dandiapi/api/migrations/0002_asset_zarr.py
  dandiapi/api/migrations/0009_remove_embargoedassetblob_dandiset_and_more.py
  dandiapi/api/migrations/0011_asset_access_metadata.py
  dandiapi/api/migrations/0013_remove_assetpath_consistent_slash_and_more.py
  dandiapi/api/migrations/0018_auditrecord_admin_auditrecord_description_and_more.py
  dandiapi/api/models/asset.py
  dandiapi/api/models/asset_paths.py
  dandiapi/api/models/audit.py
  dandiapi/api/models/version.py
  dandiapi/urls.py
  dandiapi/zarr/migrations/0001_initial_v2.py
  dandiapi/zarr/models.py
  uv.lock
Labels: internal, dependencies

#2537 Add admin user list endpoint
  dandiapi/api/tests/test_users.py
  dandiapi/api/views/__init__.py
  dandiapi/api/views/users.py
  dandiapi/urls.py
Labels: enhancement, minor, release

#2535 Improve documentation for development setup
  DEVELOPMENT.md
Labels: documentation

#2542 Fix intermittent login error
  web/package.json
  web/yarn.lock
Labels: patch, release, client

#2546 Remove unnecessary `format` argument from `APIRequestFactory` instances
  dandiapi/api/tests/test_asset.py
  dandiapi/api/tests/test_audit.py
  dandiapi/api/tests/test_dandiset.py
  dandiapi/api/tests/test_permission.py
  dandiapi/api/tests/test_upload.py
  dandiapi/api/tests/test_users.py
  dandiapi/api/tests/test_version.py
  dandiapi/zarr/tests/test_zarr.py
  dandiapi/zarr/tests/test_zarr_upload.py
Labels: tests

#2559 Remove use of dandiset* test fixtures
  dandiapi/api/tests/test_asset.py
  dandiapi/api/tests/test_audit.py
  dandiapi/api/tests/test_dandiset.py
  dandiapi/api/tests/test_embargo.py
  dandiapi/api/tests/test_permission.py
  dandiapi/api/tests/test_stats.py
  dandiapi/api/tests/test_unembargo.py
  dandiapi/api/tests/test_upload.py
  dandiapi/api/tests/test_version.py
  dandiapi/api/tests/test_webdav.py
  dandiapi/zarr/tests/test_ingest_zarr_archive.py
  dandiapi/zarr/tests/test_zarr.py
Labels: tests

#2560 Improve Zarr upload tests
  dandiapi/api/tests/test_audit.py
  dandiapi/zarr/tests/test_zarr_upload.py
Labels: tests

#2552 Add management command to delete extra manifest files
  dandiapi/api/management/commands/delete_malformed_manifests.py
Labels: patch, release

#2562 Create a `ZarrFileFactory`
  dandiapi/api/tests/test_audit.py
  dandiapi/api/tests/test_unembargo.py
  dandiapi/conftest.py
  dandiapi/zarr/tests/factories.py
  dandiapi/zarr/tests/test_zarr_upload.py
  dandiapi/zarr/tests/utils.py
Labels: tests

#2568 Remove `get_boto_client` and `get_storage_params` helpers
  dandiapi/api/management/commands/delete_malformed_manifests.py
  dandiapi/api/migrations/0001_initial_v2.py
  dandiapi/api/services/embargo/utils.py
  dandiapi/api/storage.py
  dandiapi/api/tests/test_unembargo.py
  dandiapi/zarr/models.py
  dandiapi/zarr/tasks/__init__.py
  dandiapi/zarr/views/__init__.py
Labels: internal
