Repository dandi/dandi-archive, pull requests merged in 2025-06, with the labels that each got.

#2400 Give explicit instructions on where to get code and check/set port for django DB
  DEVELOPMENT.md
  dev/.env.docker-compose
  dev/.env.docker-compose-native
Labels: documentation

#2229 Add staging rename design doc
  doc/design/staging-rename.md
Labels: documentation, design-doc

#2403 Prune web/ from sdist of dandiarchive/ and thus when uploading to heroku
  MANIFEST.in
Labels: release, internal, administration

#2408 ENH: allow googlebot also /search endpoint and for filtered listing of assets
  dandiapi/api/tests/test_robots.py
  dandiapi/api/views/robots.py
Labels: patch
