Repository dandi/dandi-archive, pull requests merged in 2025-07, with the labels that each got.

#2422 Fix missing species on search page
  dandiapi/search/views/__init__.py
  web/src/components/Search/forms/SpeciesForm.vue
Labels: bug, patch, release

#2437 Fix type checking error
  web/src/components/Search/forms/SpeciesForm.vue
Labels: bug

#2438 Remove the rest of `dandiapi.analytics`
  dandiapi/analytics/__init__.py
  dandiapi/analytics/apps.py
  dandiapi/analytics/migrations/0001_initial_v2.py
  dandiapi/analytics/migrations/0002_remove_processeds3log_analytics_processeds3log_unique_name_embargoed_and_more.py
  dandiapi/analytics/migrations/0003_delete_processeds3log.py
  dandiapi/analytics/migrations/__init__.py
  dandiapi/settings.py
Labels: internal

#2436 Use 1. for all items in markdown ordered lists
  DEVELOPMENT.md
Labels: documentation

#2414 ENH: add filtering capabilities to NestedAssetViewSet
  dandiapi/api/tests/test_asset.py
  dandiapi/api/views/asset.py
Labels: enhancement, release

#2441 Update hardcoded staging URL
  web/src/views/DandisetLandingView/ExternalDandisetServicesDialog.vue
Labels: bug, release

#2440 Add source script for fish shell
  dev/export-env-fish.sh
Labels: DX, internal

#2446 Point staging web app at sandbox URL
  web/netlify.toml
Labels: enhancement, release, internal
