Repository dandi/dandi-archive, pull requests merged in 2025-05, with the labels that each got.

#2389 Fix Frontend CI Failing: remove " " from the Sign In/Up button names
  e2e/utils.ts
Labels: tests

#2383 Bump dandischema to 0.11.1 in API dependencies; bring back "yarn migrate" command to update typings for frontend/schema
  setup.py
  web/README.md
  web/eslint.config.js
  web/package.json
  web/src/migrate.ts
  web/src/types/schema.ts
  web/yarn.lock
Labels: minor, dependencies, administration

#2373 Fix formatting of approved user message template
  dandiapi/api/templates/api/mail/approved_user_message.txt
Labels: patch

#2371 Fix broken/out-of-date docs links
  web/src/components/DandiFooter.vue
  web/src/components/FileBrowser/FileUploadInstructions.vue
  web/src/views/CreateDandisetView/CreateDandisetView.vue
  web/src/views/DandisetLandingView/DownloadDialog.vue
Labels: UX, patch, vendorization
