Repository dandi/dandi-archive, pull requests merged in 2025-04, with the labels that each got.

#2241 update test doi server
  web/netlify.toml
Labels: client

#2317 Fix validation issue with vue/vjsf 3
  e2e/tests/meditor.spec.ts
  web/src/components/Meditor/Meditor.vue
  web/src/components/Meditor/utils.ts
Labels: patch, release

#2321 Conditionally display sticky banner
  web/README.md
  web/src/components/FooterBanner.vue
  web/src/views/HomeView/HomeView.vue
  web/src/views/HomeView/StatsBar.vue
Labels: minor, release

#2283 Add warning alert for test dandisets in CreateDandisetView
  web/src/utils/constants.ts
  web/src/views/CreateDandisetView/CreateDandisetView.vue
Labels: minor, release

#2285 DOC: fixup description of the interaction with auto for releases based on labels
  doc/design/deployment-1.md
Labels: documentation

#2320 Unpin `django-oauth-toolkit`, generate migrations for downstream `StagingApplication`
  dandiapi/api/migrations/0021_stagingapplication_allowed_origins_and_more.py
  setup.py
Labels: dependencies

#2326 Require minimum version of 2.0 for django-oauth-toolkit
  setup.py
Labels: patch, dependencies

#2327 Update swagger/redocs urls to align with Resonant
  dandiapi/urls.py
Labels: internal

#2331 Switch staging back to builtin oauth `Application`
  dandiapi/settings.py
Labels: internal

#2332 Switch from `runtime.txt` to `.python-version`
  .github/workflows/backend-ci.yml
  .github/workflows/backend-production-deploy.yml
  .github/workflows/backend-staging-deploy.yml
  .github/workflows/frontend-ci.yml
  .python-version
  runtime.txt
Labels: internal

#2335 Fix oauth2 setting
  dandiapi/settings.py
Labels: patch

#2337 Don't override oauth2_provider settings dict
  dandiapi/settings.py
Labels: patch

#2338 Revert OAuth model change
  dandiapi/settings.py
Labels: internal

#2329 Move banner with info blurb to top of all pages
  web/src/App.vue
  web/src/components/InfoBanner.vue
  web/src/views/HomeView/HomeView.vue
Labels: minor, release

#2341 Remove unneeded data from playwright test fixture
  dandiapi/api/fixtures/README.md
  dandiapi/api/fixtures/playwright.json.xz
Labels: tests

#2343 Integrate `garbage_collection` service into `collect_garbage.py`
  dandiapi/api/management/commands/collect_garbage.py
  dandiapi/api/services/garbage_collection/__init__.py
  dandiapi/api/services/garbage_collection/asset_blob.py
  dandiapi/api/services/garbage_collection/upload.py
  dandiapi/api/tests/test_garbage_collection.py
Labels: release, internal

#2340 Auto-allow people with `@nih.gov` and `@janelia.hhmi.org` email addresses
  dandiapi/api/views/auth.py
Labels: minor

#2351 Remove import_dandisets command from docs
  DEVELOPMENT.md
Labels: documentation

#2339 Convert StagingApplication to a proxy model
  dandiapi/api/migrations/0022_delete_stagingapplication_stagingapplication.py
  dandiapi/api/models/oauth.py
Labels: internal

#2357 Revert "Convert StagingApplication to a proxy model"
  dandiapi/api/migrations/0022_delete_stagingapplication_stagingapplication.py
  dandiapi/api/models/oauth.py
Labels: skip-release

#2360 Make eslint fail on warning
  web/package.json
Labels: internal, tests

#2358 Update sorting controls for Dandisets page
  web/src/components/DandisetsPage.vue
Labels: minor

#2272 Fix display of dandisets with many owners
  dandiapi/api/management/commands/create_dev_dandiset.py
  setup.py
  web/src/views/DandisetLandingView/DandisetOwners.vue
Labels: minor, release

#2366 Remove margin around DandisetList
  web/src/components/DandisetsPage.vue
Labels: minor, release
