Repository dandi/dandi-archive, pull requests merged in 2025-08, with the labels that each got.

#2452 DLP Sidebar Design
  e2e/tests/meditor.spec.ts
  web/src/views/DandisetLandingView/CiteAsDialog.vue
  web/src/views/DandisetLandingView/ContactDialog.vue
  web/src/views/DandisetLandingView/DandisetActions.vue
  web/src/views/DandisetLandingView/DandisetOwners.vue
  web/src/views/DandisetLandingView/DandisetPublish.vue
  web/src/views/DandisetLandingView/DandisetSidebar.vue
  web/src/views/DandisetLandingView/DandisetValidationErrors.vue
  web/src/views/DandisetLandingView/DownloadDialog.vue
  web/src/views/DandisetLandingView/ExternalDandisetServicesDialog.vue
Labels: bug, design, release

#2466 Switch from setuptools to hatchling
  LICENSE
  MANIFEST.in
  NOTICE
  pyproject.toml
  setup.cfg
  setup.py
Labels: internal

#2469 Add `requirements.txt`
  requirements.txt
Labels: internal

#2470 Ensure `requirements.txt` is included in sdist
  pyproject.toml
Labels: internal

#2472 Include other files needed by Heroku in sdist
  pyproject.toml
Labels: internal

#2468 Miscellaneous improvements
  .gitattributes
  .gitignore
  DEVELOPMENT.md
  dev/.env.docker-compose
  dev/.env.docker-compose-native
  docker-compose.yml
Labels: internal

#2474 Fix broken behavior when text includes single quotes
  web/src/components/Meditor/Meditor.vue
Labels: patch, release

#2475 Remove unused code
  dandiapi/api/copy.py
  dandiapi/settings.py
Labels: internal

#2406 Improve and update doc regarding the `psycopg` dependency and its system dependencies
  DEVELOPMENT.md
Labels: documentation

#2455 Add support to open NIfTI-Zarr assets with the OME-Zarr Validator external service
  web/src/views/FileBrowserView/FileBrowser.vue
Labels: enhancement, release

#2476 Fix "union-attr" type errors
  dandiapi/api/models/asset.py
  dandiapi/api/tests/test_asset.py
  dandiapi/api/tests/test_asset_paths.py
  dandiapi/api/tests/test_tasks.py
  dandiapi/api/views/asset.py
  dandiapi/api/views/pagination.py
  dandiapi/zarr/tests/test_ingest_zarr_archive.py
Labels: internal

#2465 Improvements to GitHub Actions
  .github/workflows/backend-ci.yml
  .github/workflows/backend-production-deploy.yml
  .github/workflows/backend-staging-deploy.yml
  .github/workflows/cli-integration.yml
  .github/workflows/frontend-ci.yml
  .github/workflows/release.yml
Labels: internal

#2489 Support embargo tags in generated zarr upload URLs
  dandiapi/api/storage.py
  dandiapi/zarr/models.py
Labels: patch, release

#2490 Revert change to github token
  .github/workflows/release.yml
Labels: patch, release

#2491 Revert change to github token again
  .github/workflows/backend-production-deploy.yml
Labels: patch

#2496 Revert "Temporarily point CLI tests at PR branch"
  .github/workflows/cli-integration.yml
Labels: tests

#2451 Add middleware/logger to log username on every request
  dandiapi/api/logging.py
  dandiapi/settings/base.py
Labels: release, internal

#2505 Fix Dockerfile for dev django
  dev/django.Dockerfile
Labels: internal

#2509 Fix Bug in collect_garbage.py with printing
  dandiapi/api/management/commands/collect_garbage.py
Labels: internal

#2511 Include asset size in audit record
  dandiapi/api/services/audit/__init__.py
Labels: internal

#2504 Fix avatar and new dandiset button line break issue in header
  e2e/tests/dandisetsPage.spec.ts
  web/src/components/AppBar/AppBar.vue
Labels: enhancement, minor, release

#2512 Fix broken links: Terms and Policies
  web/src/components/DandiFooter.vue
Labels: patch, client

#2514 Use allauth setting to restrict prod to github auth
  dandiapi/settings/production.py
  dandiapi/urls.py
Labels: internal

#2516 Apply embargo functionality to dandiset manifest files
  dandiapi/api/management/commands/rectify_manifest_tags.py
  dandiapi/api/manifests.py
  dandiapi/api/services/embargo/utils.py
  dandiapi/api/tests/test_manifests.py
  dandiapi/api/tests/test_unembargo.py
Labels: patch, release

#2467 Add endpoint for retrieving custom audit info
  dandiapi/api/migrations/0025_auditrecord_timestamp_index.py
  dandiapi/api/models/audit.py
  dandiapi/api/permissions.py
  dandiapi/api/tests/test_audit.py
  dandiapi/api/views/__init__.py
  dandiapi/api/views/audit.py
  dandiapi/urls.py
Labels: enhancement, release
